version: '3.7'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        ports:
            - '27017:27017'
        networks:
            - backend
        env_file: .env
        volumes:
            - mongodbdata:/data/db

    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        ports:
            - '5000:5000'
        env_file: .env
        volumes:
            - appdata:/app_data
            - ./server:/app
        depends_on:
            - mongodb
        networks:
            - frontend
            - backend

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
        ports:
            - '3000:3000'
        env_file: .env
        volumes:
            - ./client:/app
            - /app/node_modules

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
